/home/cii/anaconda3/envs/test_pytorch/bin/spisonet.py refine subtomo.star
Traceback (most recent call last):
  File "/home/cii/software/spIsoNet/bin/refine.py", line 30, in run
    args = run_whole(args)
  File "/home/cii/software/spIsoNet/bin/refine.py", line 160, in run_whole
    md.read(args.subtomo_star)
  File "/home/cii/software/spIsoNet/util/metadata.py", line 129, in read
    f = open(input_star)
FileNotFoundError: [Errno 2] No such file or directory: 'subtomo.star'
/home/cii/software/spIsoNet/bin/spisonet.py refine subtomo_50.star --gpuID 0 --remove_intermediate False --epochs 2
Traceback (most recent call last):
  File "/home/cii/software/spIsoNet/bin/refine.py", line 32, in run
    args = run_whole(args)
  File "/home/cii/software/spIsoNet/bin/refine.py", line 175, in run_whole
    md.read(args.subtomo_star)
  File "/home/cii/software/spIsoNet/util/metadata.py", line 129, in read
    f = open(input_star)
FileNotFoundError: [Errno 2] No such file or directory: 'subtomo_50.star'
